### PR TITLE
Add GoogleMaps Literal helpers

### PR DESCRIPTION
**Pull request by alfonsogarciacaro**
Just edited the file with GH online IDE, haven't really tested it :)

### CODE REVIEW

**Comment by forki** [comment]
thanks!

**Comment by forki** [comment]
image


looks like this version doesn't play well with Thoth.

**Comment by forki** [comment]
ok this is unrelated this PR - it's because og how ts2fable does things here: https://github.com/fable-compiler/Fable.ReactGoogleMaps/pull/3/files#diff-4f3dc4fe59b657fcd200a8c4a42c4f57R1928

**Comment by MangelMaxime** [comment]
@forki You need to add an extra coder.

[Documentation can be found here](https://mangelmaxime.github.io/Thoth/json/v3.html#extra-coders)

**Comment by forki** [comment]
yes but I didn't need that before fable 2.2 push. It worked seamless with SSR

**Comment by MangelMaxime** [comment]
Is the property marked as optional?

Like `LatLngLiteral option`?

**Comment by forki** [comment]
IIRC yes. Can verify on Thursday

Maxime Mangel <notifications@github.com> schrieb am Di., 30. Apr. 2019,
15:40:

**Comment by forki** [comment]
yes it's option and None. what can I do?

**Comment by MangelMaxime** [comment]
I think this is because Alfonso changed the bahaviour of the decoder. It's generate the error at the generation time and not usage time.

So I suspect, `'T option` has been broken. Before, in the case of `'T option` the decoder was falling only if we didn't provide `None`. You can open an issue / PR with reproduction code [here](https://github.com/thoth-org/Thoth.Json).

And for now, provide a coder for `LatLngLiteral` even if it generates `nil/null` every time just so the error isn't thrown at generation time. [Doc](https://mangelmaxime.github.io/Thoth/json/v3.html#extra-coders)

**Comment by forki** [comment]
I have many other cases like this one. I'd probably need to wait with the
fable update.

Will open an issue

Am Do., 2. Mai 2019 um 09:07 Uhr schrieb Maxime Mangel <
notifications@github.com>:

**Comment by forki** [comment]
mhm thoth.json seems to work fine with fable. I assume it's in the .NET part?

**Comment by alfonsogarciacaro** [comment]
Thoth.Json 2 auto encoding had a [simple and optimistic logic](https://github.com/MangelMaxime/Thoth/blob/1fe6d28a17b13561831b119a62f943118a847773/src/Thoth.Json/Encode.fs#L317-L335) but Thoth.Json 3 generates actual encoders using reflection. Because the literals are just interfaces, the encoders cannot be generated. I assume they would work if you change the Literals to records and edit the Literal module as follows:

```fsharp
// type LatLngLiteral =
//     { lat: float
//       lng: float }

// type LatLngBoundsLiteral =
//     { north: float
//       east: float
//       south: float
//       west: float }

module Literal =
    let createLatLng lat lng : LatLngLiteral =
        { lat = lat; lng = lng }

    let createLatLngBounds north east south west : LatLngBoundsLiteral =
        { north = north
          east = east
          south = south
          west = west }

    // Not sure about CircleLiteral
```

**Comment by alfonsogarciacaro** [comment]
BTW, how do you create Literals on .NET? `jsOptions` should only work with Fable.

**Comment by forki** [comment]
I don't create the literals on .NET - the LatLng stuff are optionals and are always None in SSR

**Comment by forki** [comment]
for reference: https://github.com/thoth-org/Thoth.Json/pull/5
it does not matter if it's a class or interface. Both cases work in the tests. But it does not work in my app for unknown reasons.

**Pull request merged**
