### PR TITLE
Fix build

### PR DESCRIPTION
**Pull request by alfonsogarciacaro**
I've copied the GoogleMaps bindings to this repo for new. The project is building now, I assume it should work but I haven't tested it :)

### CODE REVIEW

**Comment by nojaf** [comment]
Please publish GoogleMaps binding without React components to nuget.
In another project I'm using GoogleMaps without React, it be nice if that still works.

**Comment by forki** [comment]
@nojaf can you please send PR?

**Comment by alfonsogarciacaro** [comment]
@nojaf For that we need a volunteer that takes the GoogleMaps.fs file, puts it in its own repo (if it's only bindings, you can [omit this line](https://github.com/fable-compiler/Fable.ReactGoogleMaps/blob/70a7b8050723518676f85f84adc3003c836f6a2f/src/Fable.ReactGoogleMaps.fsproj#L17)) and takes care of maintaining it ;)

**Comment by nojaf** [comment]
Hmm yeah the easy way is to use paket, grab the single file and be done with it.
I might extract the file to its own repo, I would be ok with maintaining it.
I'll try to cook something in the coming weeks.

**Pull request merged**
